myproject/customer/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', home, name="homepage"),
    path('home/', register, name="home"),
    path('login/', login_view, name='customer_login'),
    path('order/', order_food, name='order_food'),
    path('cart/', view_cart, name='view_cart'),
    path('cart/remove/<str:food_id>', remove_item, name='remove_item'),
    path('cart/add/<str:food_id>/', add_to_cart, name='add_to_cart'),
    path('cart/update/<str:food_id>/', update_cart, name='update_cart'),
    path('cart/remove/<str:food_id>/', remove_item, name='remove_item'),
    path('thankyou/', thank_you, name='thank_you'),
    path('customer/dashboard/', customer_dashboard, name = 'customer_dashboard'),
    path('customer_logout/', LogoutView.as_view(), name = 'customer_logout'),
]

myproject/management/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('dashboard/', manager_login, name="manager_login"),
    path('menu/', show_menu, name="show_menu"),
    path('add_menu/', add_menu, name="add_menu"),
    path('update_menu/', update_menu, name="update_menu"),
    path('update_menu/<int:menu_id>', update_item, name="update_item"),
    path('customer_orders/', customer_orders, name="customer_orders"),
    path('update_order/<str:id>/', update_order, name="update_order"),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/', include('management.urls')),
    # path('home/', include('customer.urls')),

    path('', include('customer.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_DIRS)
urlpatterns += [path('silk/', include("silk.urls")),]

myproject/management/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("ENter Email")
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is False:
            raise ValueError
        if extra_fields.get('is_superuser') is False:
            raise ValueError
        
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.is_customer = True
        user.is_manager = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=True)
    is_manager = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        return self.is_superuser
    
    def has_module_perms(self, app_label):
        return self.is_superuser


class Manager(models.Model):
    manager_name = models.CharField(max_length=100)
    manager_email = models.EmailField(max_length=100)
    manager_city = models.CharField(max_length=50)
    manager_phone = models.IntegerField()
    manager_password = models.CharField(max_length=100)

    def __str__(self):
        return self.manager_name

class Menu(models.Model):
    categories = (
        ('starters', "starters"),
        ('Chinese', "Chinese"),
        ("indian", 'indian'),
        ('snacks', "snacks"),
        ('Dessert', "Dessert"),
        ('Breads', 'Breads'),
        ('south indian', 'south indian'),
        ('main course', "main course"),
    )
    vegetarian = (
        ('Vegetarian', 'Vegetarian'),
        ('Non Vegetarian', 'Non Vegetarian'),
    )
    # food_id = models.CharField(max_length = 10)
    food_name = models.CharField(max_length = 50)
    food_desc = models.CharField(max_length = 200)
    food_category = models.CharField(max_length=50, choices=categories)
    food_type = models.CharField(max_length=20, choices=vegetarian)
    food_price = models.IntegerField(default = 0)
    food_image = models.ImageField(upload_to="media/", default= None)
    food_quantity = models.IntegerField(default=10)


    def __str__(self):
        return self.food_name

myproject/management/forms.py
from django import forms
from .models import Manager, Menu 

class LoginForm(forms.ModelForm):
    class Meta:
        model = Manager
        fields = '__all__'
        labels = {'manager_name' : "enter your name",
                  'manager_email' : "enter your email",
                  'manager_city' : "enter your city",
                  'manager_phone' : "enter your phone",
                  'manager_password' : 'enter your password',
                  }
        
class AddMenu(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['food_name', 'food_desc', 'food_category', 'food_type', 'food_price', 'food_image']
        widgets = {
             'food_name' : forms.TextInput(attrs={'class' : "mail_text", 'placeholder': "Enter Food Name"}),
             'food_desc' : forms.TextInput(attrs={'class' : "mail_text", 'placeholder': "Enter Food Description"}),
             'food_category' : forms.Select(attrs={'class' : "mail_text"}),
             'food_type' : forms.Select(attrs={'class' : "mail_text"}),
        }
        labels = {'food_name' : "",
                  'food_desc' : "",
                  }

    

myproject/management/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .forms import AddMenu
from django.http import HttpResponseRedirect
from .models import Menu
from customer.models import Orders
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.
@login_required(login_url="/login")
def manager_login(request):
    return render(request, 'dashboard.html')

@login_required(login_url="/login")
def show_menu(request):
    data = Menu.objects.all()
    paginator = Paginator(data, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'viewmenu.html', {'data' : page_obj})

@login_required(login_url="/login")
def add_menu(request):
    if request.method == "POST":
        form = AddMenu(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/manager/menu')
    else:
        form = AddMenu()
    return render(request, 'addmenu.html', {'form' : form})

@login_required(login_url="/login")
def update_item(request, menu_id):
    query = request.POST.get("update_dish")
    if query=="update":
        price = request.POST.get('price')
        Menu.objects.filter(pk = menu_id).update(food_price = price)
    else:
        Menu.objects.filter(pk = menu_id).delete()
    return redirect('update_menu')


@login_required(login_url="/login")
def customer_orders(request):
    status = Q(status__iexact="PENDING")| Q(status__iexact="ACCEPTED")| Q(status__iexact="REJECTED")
    pending_orders = Orders.objects.filter(status)
    return render(request, 'orders.html', {'items': pending_orders})


@login_required(login_url="/login")
def update_order(request, id):
    accept = request.POST.get('accept')
    if accept == "accept":
        Orders.objects.filter(name_id = id, status = "PENDING").update(status = "ACCEPTED")
    else:
        Orders.objects.filter(name_id = id, status = "PENDING").update(status = "REJECTED")
    
    return redirect('customer_orders')


@login_required(login_url="/login")
def update_menu(request):
    data = Menu.objects.all()
    paginator = Paginator(data, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'update_menu.html', {'data' : page_obj})

myproject/management/templates/addmenu.html
{% extends "/home/nihal/restaurent/myproject/customer/templates/register.html" %}
{% load static %}

{% block formtitle %}ADD Menu{% endblock formtitle %}

{% block styles %}
<style>
    .pagination {
    display: none;
    }

    .add_bt{
        width: 100%;
        text-align: center;
        font-size: 16px;
        color: #fefefd;
        background-color: #d07d6b;
        padding: 10px;
        text-transform: uppercase;
        margin-top: 20px;
        display: block;
        cursor: pointer;
        font-weight: bold;
        border-radius: 5px;
        margin-bottom: 20px;
        font-family: 'Poppins', sans-serif;
    }

    .custom-file-upload {
        display: inline-block;
        padding: 10px 20px;
        background-color: #d07d6b;
        color: white;
        font-size: 16px;
        border: none;
        margin-top : 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    .choices{
        background-color : #efefef;
        padding: 11px 20px;
        width : 100%;
        border : none;
        border-radius : 40px;
        margin-top: 20px;
        font-size: 16px;
        color: #2e2e2d;
    }

    .choices::placeholder{
        font-size: 16px;
        color: #2e2e2d;
    }
</style>
{% endblock styles %}

{% block form %}
<form action="" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {% comment %} {{form}} {% endcomment %}
    <div>
        {{ form.food_name }}
    </div>
    
    <div>
        {{ form.food_desc }}
    </div>
    
    <!-- Food Category Dropdown -->
    <div>

        <select name="food_category" id="id_food_category" class="choices" style='padding : 15px 20px 15px 20px'>
            {% for value, label in form.food_category.field.choices %}
                <option value="{{ value }}" {% if form.food_category.value == value %}selected{% endif %}>
                    {% if label == '---------' %}Enter Food Category {% else %}{{ label|title }}{% endif %}
                </option>
            {% endfor %}
        </select>
    </div>
    
    <!-- Food Type Dropdown -->
    <div>

        <select name="food_type" id="id_food_type" class='choices' style='padding : 15px 20px 15px 20px'>
            {% for value, label in form.food_type.field.choices %}
                <option value="{{ value }}" {% if form.food_type.value == value %}selected{% endif %}>
                    {% if label == '---------' %}Enter Food Type {% else %}{{ label }}{% endif %}
                </option>
            {% endfor %}
        </select>
    </div>
    
    <div>
        {% comment %} <label for="id_food_price">Food Price</label> {% endcomment %}
        <input type="number" name="food_price" value="" required id="id_food_price" class='choices' placeholder='Enter Food Price'>
        {% comment %} {{ form.food_price }} {% endcomment %}
    </div>
    <div>
        <label for="id_food_image" class='custom-file-upload'>Upload Food image</label>
        <input type="file" name="food_image" id="id_food_image"  value='Upload File' class='pagination'>
    </div>

    <div class="send_bt"><input type = 'submit' value = 'Add Dish' class = 'add_bt'>
    </div>
</form>
{% endblock form %}

{% block addcss %}

      <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="css/style.css">
      <link rel="stylesheet" href="css/responsive.css">
      <link rel="icon" href="images/fevicon.png" type="image/gif" />
      {% comment %} <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap" rel="stylesheet"> {% endcomment %}
      <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
      {% comment %} <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"> {% endcomment %}

{% endblock addcss %}

myproject/management/templates/dashboard.html
{% extends "/home/nihal/restaurent/myproject/customer/templates/customerdashboard.html" %}
{% load static %}

{% block customer %}

<li class="nav-item">
    <a href='{% url "show_menu" %}' class="nav-link"> View Menu </a>
</li>
<li class="nav-item">
    <a href='{% url "add_menu" %}' class="nav-link"> Add Menu </a>
</li>
<li class="nav-item">
    <a href='{% url "update_menu" %}' class="nav-link"> Update Menu </a>
</li>
<li class="nav-item">
    <a href='{% url "customer_orders" %}' class="nav-link"> Accept/Reject Orders </a>
</li>
{% endblock customer %}

{% block banner_content %}
<h1 class="banner_taital">DashBoard</h1>
<p class="banner_text">Click the button below to accept or reject Orders</p>
{% endblock banner_content %}

{% block dashboard %}
<div class="about_bt"><a href='{% url "customer_orders" %}'>View Orders</a></div> 
{% endblock dashboard %}

myproject/management/templates/orders.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'cart.css'%}">
    <title>cart</title>
</head>
<body>
  <div class="dish-block">
    <h1>Orders</h1>  

      {% if  items %}
        {% for i in items %}
          {% if i.quantity > 0 %}
          <span class="dish-cart">
              <div>
                <a href=''> 
                <img src='{{i.name.food_image.url}}' alt="Pasta">
                </a>
              </div>
              <div>
                <h3>{{i.name.food_name}}</h3>
                <h4>Rs. {{i.total_price}}</h4>
                <p><b>{{i.name.food_category}} </b></p>
                <p><b>{{i.name.food_type}} </b></p>
                <p>Quantity: {{i.quantity}}</p>
                <p>Ordered By: {{i.user.name}}</p>
              </div>
              <div>

                {% if i.status == "PENDING" %}   
                  <form method='post' action='{% url "update_order" i.name.id %}'>
                    <button class="update" value='accept' type = 'submit' name='accept'>ACCEPT</button>
                    <button type='submit' value='reject' class='update' style='background-color: red;'>REJECT</button>
                    {% csrf_token %}
                  </form>
                {% else %}
                  <h1>{{i.status}}</h1>
                {% endif %} 

              </div> 
          </span>
          {% else %}
            <h3>NO ORDERS</h3>
          {% endif %}

        {% endfor %}
      {% else %}
        <h3>NO ORDERS</h3>
      {% endif %}
</body>
</html>

myproject/management/templates/update_menu.html
{% extends "viewmenu.html" %}
{% load static %}

{% block customer %}
<li class="nav-item">
    <a href='{% url "add_menu" %}' class="nav-link"> Add Menu </a>
</li>
{% endblock customer %}

{% block updateform %}
<span class="dish-list">
    {% for i in data%}
    <span class="dish-card">
            <img src='{{i.food_image.url}}' alt="{{i.food_image}}">
            <h3>{{i.food_name}}</h3>
            <p>{{i.food_category}}</p>
            <h3>Rs. {{i.food_price}}</h3>
            <h3>{{i.food_type}}</h3>
            <form action='{% url "update_item" i.id %}' method='post'>
                {% csrf_token %}
                <input type = 'number' placeholder = 'price' name='price' style="border: 1px solid black; margin-bottom: 20px; padding: 5px 10px;"><br>
                <button type='submit' name='update_dish' value='update'>Update Dish</button>
                <button type='submit' name='update_dish' value='delete'>Delete Dish</button>
            </form> 
    </span>
    {% endfor %}
</span>
{% endblock updateform %}

myproject/management/templates/viewmenu.html
{% extends "/home/nihal/restaurent/myproject/customer/templates/orderfood.html" %}


{% block banner_content %}
<p></p>
{% endblock banner_content %}

{% block styles %}
<style>
    .pagination {
    --color: #4CAF50;
    font-family: inherit;
    display: inline-block;
    width: 8em;
    height: 2.6em;
    line-height: 2.5em;
    background-color : white;
    margin: 20px;
    position: relative;
    cursor: pointer;
    overflow: hidden;
    border: 2px solid var(--color);
    transition: color 0.5s;
    z-index: 1;
    font-size: 17px;
    border-radius: 6px;
    font-weight: 500;
    color: var(--color);
    }
</style>
{% endblock styles %}


{% block customer %}
<li class="nav-item">
    <a href='{% url "add_menu" %}' class="nav-link"> Add Menu </a>
</li>
<li class="nav-item">
    <a href='{% url "update_menu" %}' class="nav-link"> Update Menu </a>
</li>
{% endblock customer %}

{% block add_bt %}
<li class="nav-item"></li>
{% endblock add_bt %}

{% block dashboard %}
<p></p>
{% endblock dashboard %}

{% block maincontent %}
<span class="container">

    {% block updateform %}
    <span class="dish-list">
        {% for i in data%}
        <span class="dish-card">
            <img src='{{i.food_image.url}}' alt="{{i.food_image}}">
            <h3>{{i.food_name}}</h3>
            <p>{{i.food_category}}</p>
            <h3>Rs. {{i.food_price}}</h3>
            <h3>{{i.food_type}}</h3>
            
        </span>
        {% endfor %}
    </span>
    {% endblock updateform %}


    {% if data.has_previous %}
        <a href="?page=1" style = 'text-decoration: none; color:#4CAF50'><button class = 'pagination'>First Page</button></a>
        <a href="?page={{ data.previous_page_number }}" style = 'text-decoration: none; color:#4CAF50'><button class = 'pagination'>Previous Page</button></a>
    
    {% endif %}

    {% if data.has_next %}
        <a href="?page={{ data.next_page_number }}" style = 'text-decoration: none; color:#4CAF50'><button class = 'pagination'>Next Page</button></a>
        <a href="?page={{ data.paginator.num_pages }}" style = 'text-decoration: none; color:#4CAF50'><button class = 'pagination'>Last Page</button></a>
    {% endif %}
</span>

{% endblock maincontent %}